stages:
  - test
  - docker_build
  - deploy

Testing and Building:
  stage: test
  image: maven:latest
  script: 
     - mvn clean package
     - cat target/site/jacoco/index.html
  artifacts:
    paths:
     - target/Diet_Management_Services-1.0.jar
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
     
Building Docker Image:
  stage: docker_build
  tags:
     - runner-1
  script: 
     - docker login -u aearavindh -p $DOCKER_PASSWORD
     - docker build -t aearavindh/diet-services:latest .
     - docker push aearavindh/diet-services:latest
     
Deployment:
  stage: deploy
  tags:
     - runner-1
  script:
     - sshpass -p $SSH_USER_PASSWORD ssh -v -o StrictHostKeyChecking=no $DEPLOYMENT_HOST sudo docker container rm -f diet
     - sshpass -p $SSH_USER_PASSWORD ssh -v -o StrictHostKeyChecking=no $DEPLOYMENT_HOST sudo docker rmi aearavindh/diet-services;sudo docker pull aearavindh/diet-services:latest
     - sshpass -p $SSH_USER_PASSWORD ssh -v -o StrictHostKeyChecking=no $DEPLOYMENT_HOST sudo docker container run -d -p 8000:8000 --name diet aearavindh/diet-services:latest
  environment:
     name: production
     url: $PRODUCTION_ENVIRONMENT
  only:
     - master
