stages:
  - test_build
  - docker_build
  - deploy

Testing and Building:
  stage: test_build
  image: maven:latest
  script: 
     - mvn clean package
     - cat target/site/jacoco/index.html
  artifacts:
    paths:
     - target/Diet_Management_Services-1.0.jar
     
Building Docker Image:
  stage: docker_build
  tags:
     - runner-1
  script: 
     - docker login -u aearavindh -p $DOCKER_PASSWORD
     - docker build -t aearavindh/diet-services:$CI_JOB_ID .
     - docker push aearavindh/diet-services:$CI_JOB_ID
     
Deployment:
  stage: deploy
  tags:
     - runner-1
  script:
     - sshpass -p $SSH_USER_PASSWORD ssh -v -o StrictHostKeyChecking=no $DEPLOYMENT_HOST sudo docker container rm -f diet-services;sudo docker container run -e MAIL_PASSWORD=$MAIL_PASSWORD -d -p 8000:8000 --name diet-services aearavindh/diet-services:$CI_JOB_ID
  environment:
     name: production
     url: $PRODUCTION_ENVIRONMENT
  only:
     - master
